### ISSUE TITLE
Gentoo:  Feedback

### ISSUE THREAD

**Issue by CJClaude** [F483/picopayments-cli-python#1]
1) "emerge -u dev-python/pip"  installs most of the environment.  Missing are  dev-python/werkzeug and dev-python/json-rpc (NOT dev-python/jsonrpclib).

2) picopayments-cli is installed in /usr/bin without execute permissions.  Quick "chmod +x" fixed that.

3) "picopayments-cli --help" works fine, however "picopayments-cli --testnet status" fails with:
  File "/usr/bin/picopayments-cli", line 21, in <module>
    result = api.__getattribute__(command)(**kwargs)
  File "/usr/lib64/python2.7/site-packages/picopayments_cli/api.py", line 221, in status
    "address": keys.address_from_wif(_load_wif()),
  File "/usr/lib64/python2.7/site-packages/picopayments_cli/api.py", line 340, in _load_wif
    with open(etc.wallet_path, 'r', encoding="utf-8") as infile:
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by CJClaude** [comment]
Hmmm, for whats its worth, a .picopayments directory was created.

storjtest@rackserv ~/.picopayments $ ls -l
total 29
-rw-r--r-- 1 storjtest storjtest 139 Dec 23 15:06 testnet.cfg
-rw-r--r-- 1 storjtest storjtest  23 Dec 23 15:06 testnet.data
-rw-r--r-- 1 storjtest storjtest  52 Dec 23 15:06 testnet.wif

**Comment by F483** [comment]
Can it be that your are using python2? I only tested on python 3 so far.

**Comment by F483** [comment]
I opened an extra issue for python 2 compatibility. https://github.com/F483/picopayments-cli-python/issues/2

**Comment by CJClaude** [comment]
Switched to python 3.4.3 via eselect and reran the install:

storjtest@rackserv ~ $ picopayments-cli --testnet status
/usr/lib64/python3.4/site-packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
{
    "connections": {},
    "wallet": {
        "address": "mkb9f5BFPi5wUg5QTFUHoJ272ZMD849HwN",
        "balances": {
            "BTC": 0
        }
    }
}

**Comment by F483** [comment]
Python 2 issue open at https://github.com/F483/picopayments-cli-python/issues/2
