### ISSUE TITLE
Is patched CP required?

### ISSUE THREAD

**Issue by unsystemizer** [F483/picopayments-cli-python#10]
https://github.com/F483/picopayments-hub/blob/master/docs/setup.md mentions a patched Counterparty library. Is that still the case? Or is that only for those who want to run the hub (while the client doesn't need to have Counterparty library/server)?
Here I can't see that mentioned, so I thought to ask.

**Comment by F483** [comment]
Only the hub requires a patched counterparty-lib and will continue to do so until the micropayment branch is merged into master and becomes part of a release.
