### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed 

### ISSUE THREAD

**Issue by unsystemizer** [F483/picopayments-cli-python#14]
The status action fails due to cert issues. I changed the verify option to false, so now it works, but maybe it'd be good to fix the cert rather than get used to this workaround although we're on testnet at the moment.
```
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
$ cat ~/.picopayments/testnet.cfg
{
  "hub_password": null,
  "hub_url": "https://micro.test.storj.io:15000/api/",
  "hub_username": null,
  "hub_verify_ssl_cert": true
}
```

This is not a picopayments-cli-python issue of course, but I can't file it against the hub server so I'm just making a note here.

**Comment by F483** [comment]
Correct cert has been added and works.
