### ISSUE TITLE
Document connect (quantity)

### ISSUE THREAD

**Issue by unsystemizer** [F483/picopayments-cli-python#15]
Can you clarify that the quantity should be stated in "satoshis" (I assume it is, since it's supposed to be an integer).
From the examples at the bottom it's not easy to conclude, which may cause troubles for users who don't have (say) "1000000" XCP, for example.

**Comment by F483** [comment]
Changed the unit description to be 'SATOSHIS' so it is more clear. https://github.com/F483/picopayments-cli-python/commit/38c8132fce582f76085f1e69f5b65dc275b98e84

```
$ picopayments-cli --testnet connect --help
usage: picopayments-cli connect [-h] [--expire_time BLOCKS]
                                [--delay_time BLOCKS]
                                ASSET SATOSHIS

positional arguments:
  ASSET                 Asset to exchange in connection.
  SATOSHIS              Quantity to be bound in the connection deposit.

optional arguments:
  -h, --help            show this help message and exit
  --expire_time BLOCKS  Time in blocks after which the deposit expires.
  --delay_time BLOCKS   Blocks hub must wait before payout.
```
