### ISSUE TITLE
Sent, Opening is now Open, Sync'd, error...

### ISSUE THREAD

**Issue by tempestb** [F483/picopayments-cli-python#19]
$ picopayments-cli --testnet sync
Traceback (most recent call last):
  File "/usr/local/bin/picopayments-cli", line 21, in <module>
    result = api.__getattribute__(command)(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/api.py", line 302, in sync
    "received_payments": client.sync()
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/mph.py", line 194, in sync
    revokes=revokes
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/rpc.py", line 90, in wrapper
    password=self.password
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/rpc.py", line 53, in auth_jsonrpc_call
    password=password, verify_ssl_cert=verify_ssl_cert)
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/rpc.py", line 42, in jsonrpc_call
    raise JsonRpcCallFailed(payload, response)
picopayments_cli.rpc.JsonRpcCallFailed: Rpc call failed! {'method': 'mph_sync', 'params': {'commit': {'script': '6352b275a914accc03007ba5d243a48bc18be30c4616b0dfd3bb88210215d43607f622d84ec54fe50d10cf222613413fb62753acb70ce0e9e47363f042ac67a914e0b7719674ae7608ab00cdd2e4577ca9dd3e3fbf882103c523a178c91be12b90ba806f86cd3184476e8079cac47096de125a4c022a43e2ac68', 'rawtx': '0100000001e716bbf0b3335567a9397da22f066203f539f12fce7713fc5d877bee8d3f1ec200000000fd44010047304402200423782d1f312d1efd978969fd27a3c74915cd2844ff5f80aba943b8a257605802201992b8819f17ad2c03906f95f72701665f63c165ece61b56018fef8d0747a31001483045022100fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036414002207fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a001514caf63522103c523a178c91be12b90ba806f86cd3184476e8079cac47096de125a4c022a43e2210215d43607f622d84ec54fe50d10cf222613413fb62753acb70ce0e9e47363f04252ae6763a914accc03007ba5d243a48bc18be30c4616b0dfd3bb882103c523a178c91be12b90ba806f86cd3184476e8079cac47096de125a4c022a43e2ac67020004b2752103c523a178c91be12b90ba806f86cd3184476e8079cac47096de125a4c022a43e2ac6868ffffffff030a4600000000000017a91490053c78bd8e64abe0ec359bc96a4aed0e95fad48700000000000000001e6a1c0f3bb57e1f7d005fd50b4bfbc9fab229068b72412b5bacaf98de383e0a4600000000000017a914c0630f9d599a3f0a4dff8200f8b5df0b915a107b8700000000'}, 'signature': '3045022046cb2622ee83a5dfd3bfb19869800623343cab0f05210142965b386c0beef9c202210085feff304e70b8fc526ab70be053429657910c30838ccc5254d58006039019a4', 'sends': [{'payee_handle': 'n2s5WgXPZvgKjtApHLk294gCditcDEKGJS', 'amount': 50, 'token': '171920ab5bb56bb458d141e3b767d3ebc2049cd17754bbed6a54b39ea8267738'}], 'revokes': [], 'next_revoke_secret_hash': 'e822fd19e3b8b408f137fa092ceda2ec1c7e8227', 'pubkey': '03c523a178c91be12b90ba806f86cd3184476e8079cac47096de125a4c022a43e2', 'handle': '6e1b4e6cc2eda99881ef67e17a11701119b7189fb78ea1d83b11977d502523ce'}, 'jsonrpc': '2.0', 'id': 0} -> {'error': {'message': 'Server error', 'code': -32000, 'data': {'message': "Invalid hexdata: 'n2s5WgXPZvgKjtApHLk294gCditcDEKGJS'", 'args': ["Invalid hexdata: 'n2s5WgXPZvgKjtApHLk294gCditcDEKGJS'"], 'type': 'InvalidHexData'}}, 'id': 0, 'jsonrpc': '2.0'}

**Comment by F483** [comment]
I see the problem, you tried to send to an address (n2s5WgXPZvgKjtApHLk294gCditcDEKGJS) instead of a payment channels handle. A payment chennel is always identified by a hex encoded handle, as you may open several payment channels with a single wallet address/key.
