### ISSUE TITLE
Ensure python 2 compatibility.

### ISSUE THREAD

**Issue by F483** [F483/picopayments-cli-python#2]
Make sure all tests and code run with python 2.

**Comment by unsystemizer** [comment]
Maybe you can change `pip install ... ` to `pip3 install ...` in the readme file (SETUP section)

Like the other guy I started with python2.7 because of those SETUP instructions.

**Comment by F483** [comment]
Good point, have done so. Will be a while until python 2 is supported as I will have to figure out a way to test it automatically.

**Comment by F483** [comment]
Since counterpartylib does not support python 2, it doesn't really make to much sense at the moment. Considering even large projects like Django and Ubuntu are discarding python 2, it may just be time to say goodbye.
