### ISSUE TITLE
Launching under Windows

### ISSUE THREAD

**Issue by tempestb** [F483/picopayments-cli-python#20]
Python 3.6 32bit

`python Scripts/picopayments-cli. --testnet status
Traceback (most recent call last):
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\werkzeug\serving.py", line 65, in <module>
    from SocketServer import ThreadingMixIn, ForkingMixIn
ModuleNotFoundError: No module named 'SocketServer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Scripts/picopayments-cli.", line 10, in <module>
    from picopayments_cli import api
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\picopayments_cli\api.py", line 5, in <module>
    from werkzeug.serving import run_simple
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\werkzeug\serving.py", line 68, in <module>
    from socketserver import ThreadingMixIn, ForkingMixIn
ImportError: cannot import name 'ForkingMixIn'`

**Comment by F483** [comment]
@littleskunk do you have a windows box you can test this on? I assume its likely a simple missing dependency.

@super3 maybe you can arrange for a windows license key to be thrown my way, I currently have one for testing.

**Comment by littleskunk** [comment]
mission accepted

**Comment by littleskunk** [comment]
Should be fixed in Werkzeug 0.11.14 and the following error in 0.11.15. That is the latest version. Easy to decide for me. I will test against 0.11.15 and hopefully come back with a pull request.

**Comment by littleskunk** [comment]
Looks good. Pull request will follow:
```
C:\Users\Skunk\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\picopayments_cli\bin>python picopayments-cli --testnet status
{
    "connections": {},
    "wallet": {
        "address": "muu8mfWPmaHP2g5jy18K6JBSM7NAvRoNiK",
        "balances": {
            "BTC": 0
        }
    }
}
```

**Comment by F483** [comment]
Release made and fix confirmed with Windows 10 Pro 64bit.
